version: '3.7'
services: 
  mysql-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - emp-app-network

  employee-rest-api:
    image: employee-rest-api
    ports:
      - "5000:8080"
    restart: always
    depends_on: # Start the depends_on first
       - mysql-server
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: mydb
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
    networks:
      - emp-app-network


networks:
  emp-app-network: